app : 'Hello World'
ci:
  podyaml: podTemplate-maven.yaml
  https_proxy: https://yourproxy:3128
  no_proxy: localhost,docker.io
  maven:
    steps:
      - "mvn -version"
      - "mvn clean install"
  kaniko:
    #registry: caternberg
    registry: krstoslovka
    application_image: spring-boot-demo
